### ISSUE TITLE
Invited rooms view controller

### ISSUE THREAD

**Issue by zhiachong** [teamnzs/ios-trivia-game#35]
Should be able to view the rooms that the user is invited to.

After clicking the game, the user is taken to countdown timer page (CountdownGameViewController)

Up to 
1. Make it into a tab
2. Flip page animation 
3. Add an info icon

**Comment by saviotsui** [comment]
completed basic ui.

TODO:
add animations.
add info icon.
navigate to countdowngameviewcontroller on click
